sonar.projectKey=matchy-ml-service
sonar.projectName=Matchy ML Prediction Service
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=models/**,**/__pycache__/**,*.pkl,project_feasibility_dataset.csv
sonar.language=py
sonar.sourceEncoding=UTF-8
